import Header from "@/components/header";
import Footer from "@/components/footer";
import './layout.css';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body>
        <div class="body">
        <Header/>
        <div class="main-container">
        {children}
        </div>
        </div>
          
          <Footer/>
            </body>
    </html>
  )
}
